site_name: 'K8S Experiment'
site_url: https://report.ice6413p.space
docs_dir: docs
nav:
  - Home: README.md
  # - Summary: summary.md
  - Installation: 
    - installation.md
    - Docker: docker.md
    - Minikube: minikube.md
    - Cluster: cluster.md
  - Container: container.md
  - Objects: objects.md

# # - [about.md, About]
# theme: 
#   # name: readthedocs
#   name: material
#   features:
#       - content.code.annotate
#       - navigation.indexes
#       - navigation.collapse

theme:
  # name: readthedocs
  name: material
  features:
    - content.tabs.link
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  # - with-pdf:
  #     author: 厉宇桐
  #     copyright: davidliyutong@sjtu.edu.cn
  #     cover_title: Lab Report
  #     cover_subtitle: ICE6413P-260-M01
  #     two_columns_level: 3

extra:
  analytics:
    provider: google
    property: G-WZKCHK54MZ

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/davidliyutong/ICE6413P-260-M01.git