site_name: K8S
site_url: https://docs.davidliyutong.top/
docs_dir: k8s
nav:
  - Home: README.md
  - Summary: summary.md
  - Installation:
    - 01_installation/README.md
    - kubeadm: 01_installation/kubeadm/README.md
    - minikube: 01_installation/minikube/README.md
  - Container:
    - Basics:
      - namespace: 10_container/10_basics/10_namespace.md
      - cgroup: 10_container/10_basics/20_cgroup.md
      - rootfs: 10_container/10_basics/30_rootfs.md
    - Docker: 
      - 10_container/20_Docker/README.md
      - Image: 
          - 10_container/20_Docker/10_image/README.md
          - Advanced: 10_container/20_Docker/10_image/advanced.md
      - Runtime: 10_container/20_Docker/15_runtime/README.md
      - Volume: 10_container/20_Docker/20_volume/README.md
      - Network: 10_container/20_Docker/25_network/README.md
      - Dockerfile: 10_container/20_Docker/30_dockerfile/README.md
      - Lab: 
        - Wordpress: 
          - 10_container/20_Docker/80_lab/10_wordpress/README.md
        - Python server: 
          - 10_container/20_Docker/80_lab/12_python-server/README.md
        - Front/Backend: 
          - 10_container/20_Docker/80_lab/14_frontbackend/README.md
      - Topics:
          - 10_container/20_Docker/90_topics/README.md
          - dind: 10_container/20_Docker/90_topics/dind/README.md
      - Docker-Compose: 
          - 10_container/20_Docker/95_docker-compose/README.md
  - Objects:
      - 20_objects/README.md
      - Config: 20_objects/01_config/README.md
      - Cluster Node: 20_objects/02_cluster-node/README.md
      - Label & Annotaion: 20_objects/03_label&annotation/README.md
      - Namespace: 20_objects/04_namespace/README.md
      - Pod: 20_objects/05_pod/README.md
      - Workload: 20_objects/10_workload/README.md
      - Service: 20_objects/15_service/README.md
      - Storage:
          - 20_objects/20_storage/README.md
          - Ceph: 20_objects/20_storage/ceph/README.md
          - CSI: 20_objects/20_storage/csi/README.md
      - Network: 
          - 20_objects/25_network/README.md
          - ingress: 20_objects/25_network/30_ingress/README.md
          - Network Polocy: 20_objects/25_network/40_network-policy/README.md
  - Components:
      - 30_components/README.md
      - aaa: 30_components/aaa/README.md
      - cni: 30_components/cni/README.md
      - kube-apiserver: 30_components/kube-apiserver/README.md
      - kube-controller-mgr: 30_components/kube-controller-mgr/README.md
      - kube-dns: 30_components/kube-dns/README.md
      - kube-proxy: 30_components/kube-proxy/README.md
      - kube-scheduler: 30_components/kube-scheduler/README.md
      - kubelet: 30_components/kubelet/README.md
      - metric-server: 30_components/metric-server/README.md
      - prometheus: 30_components/prometheus/README.md
  - Helm:
      - 50_helm/README.md
  - Operator:
      - 60_operator/README.md
  - Lab:
      - 90_lab/README.md
      - wordpress: 90_lab/wordpress/README.md

# - [about.md, About]
theme: 
  name: material
  # name: material
  features:
      - content.code.annotate
      - navigation.indexes
      - navigation.collapse

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  analytics:
    provider: google
    property: G-H7DVLG44WM

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js